# https://taskfile.dev

version: '3'

tasks:
  create-parser:
    cmds:
      - java -jar ./lib/antlr-4.12.0-complete.jar -Dlanguage=Go ./grammar/tiger.g4 -no-listener -visitor -o ./parser
      - mv parser/grammar/* parser
      - rm -d parser/grammar
    silent: true
